name: Build and Release Next.js web application
on: push
  branches:
    - main
jobs:
  build-project:
    name: Build Next.js application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build static website
        run: npm run build
      - name: Upload static website
        uses: actions/upload-artifact@v2
        with:
          name: static-site
          path: out/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: out/
